### ISSUE TITLE
singularity hub

### ISSUE THREAD

**Issue by vsoch** [qobilidop/fire-cgm#1]
heyo @qobilidop ! I am really glad that you are using Singularity Hub for your repo! I see that you are pushing quite frequently, and there are already 41 images in your collection:

https://singularity-hub.org/collections/138/

Since we build (and store) every time you build, and are providing this for free, I would ask if you wouldn't mind:

1. cleaning up the builds you don't need (eg, with delete)
2. turning off the collection for building when you know you will be pushing a lot
3. connecting a different branch to be built on the hub, and only push here when you are sure you are ready for a build.

Is there a different workflow that would be easier or more useful for you? Thanks for the feedback!

**Comment by qobilidop** [comment]
@vsoch Thanks for notifying me! I'm very sorry for abusing the service. I've deleted redundant builds and turned off the auto building. I'll keep those in mind in the future.

**Comment by vsoch** [comment]
no problemo! Haha, it made me very happy to see your usage, actually! Thanks for the speedy response, and please let me know if you have any feature requests or ideas! I'm developing a few updates for singularity hub, and all feedback is appreciated.

**Comment by qobilidop** [comment]
@vsoch sure I'll let you know if I have any. And thanks for your effort to develop and maintain such a great software!
